# /etc/samba/smb.conf, non-comment lines only (snapshot 2026-10-07)
[global]
   workgroup = WORKGROUP
   server string = motispiratia
   netbios name = motispiratia
   security = user
   map to guest = Bad User
   dns proxy = no

[Songs]
   path = /home/sulimanza/nexus/songs
   browseable = yes
   writable = yes
   valid users = sulimanza
   force user = sulimanza
   create mask = 0664
   directory mask = 0775

[Media]
  path = /mnt/storage
  browseable = yes
  writable = yes
  valid users = sulimanza
  force user = sulimanza
  create mask = 0664
  directory mask = 0775
